infra-oncall:
  - infra_schedule
  - pratik.vasa@zuddl.com
  - vedha@zuddl.com
eng-oncall:
  - "event-hosting_schedule"
  - dig_schedule
  - "event-marketing_schedule"
  - vedha@zuddl.com
  - satyadeep@zuddl.com