FROM golang:1.18.2-alpine3.15 as build

ENV CI=true \
    CGO_ENABLED=0 \
    GO111MODULE=on

WORKDIR /app

ADD . .

RUN apk add --no-cache git curl
RUN CGO_ENABLED=0 GOOS=linux go build -o ./out/opsgin

FROM alpine:3.15

COPY --from=build /app/out/opsgin /opt/opsgin

ENTRYPOINT ["/opt/opsgin"]